version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      codefeednet:
        ipv4_address: 172.20.1.1

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.20.1.2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - "zookeeper"
    networks:
      codefeednet:
        ipv4_address: 172.20.1.2

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      codefeednet:
        ipv4_address: 172.20.1.3

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      codefeednet:
        ipv4_address: 172.20.1.4

networks:
  codefeednet:
    ipam:
      driver: default
      config:
        - subnet: 172.20.1.0/24